apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/galloro-gke/pipeline:1.0.1
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
